### ISSUE TITLE
Jupyterlab_discovery enabled but not working (red cross)

### ISSUE THREAD

**Issue by mocquin** [vidartf/jupyterlab_discovery#10]
Hi,

I updated my Jlab install, and wanted to try this extension, but I'm getting this at the lunch of jlab  
``
[W 19:35:09.358 LabApp] Error loading server extension jupyterlab_discovery
    Traceback (most recent call last):  
      File ".../anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1549, in init_server_extensions  
        func(self)  
      File ".../anaconda3/lib/python3.6/site-packages/jupyterlab_discovery/server_extension.py", line 18, in load_jupyter_server_extension  
        from .handlers import (
      File ".../anaconda3/lib/python3.6/site-packages/jupyterlab_discovery/handlers.py", line 25, in <module>  
        from jupyterlab.commands import (  
    ImportError: cannot import name '_read_package'
``

when lauching 
``
jupyter labextension list
``
all my enabled-and-fully-working extensions are displaying "enabled OK", but for this extension I'm getting a red cross: 
``
jupyterlab_discovery v5.1.2  enabled   X
``

I'm guessing I should reinstall some things ?

In any case, thanks a lot for the extension !

**Comment by vidartf** [comment]
The newest versions of JupyterLab should have this as part of the core. See the instructions here: https://github.com/vidartf/jupyterlab_discovery/issues/9#issuecomment-410989215

**Comment by vidartf** [comment]
I've also just updated the README to reflect this.
